config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :bookings
  get "/admin", to: "admins#home"
  get "/admin/users", to: "admins#users"
  get "/admin/users/show/:id(.:format)", to: "admins#show", as: 'admin_users_show'
  match '/users/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy_user
  get "/booking/download/:id(.:format)", to: "bookings#download_pdf", as: 'download_pdf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    # validates :place, presence: true
    # validates :movie, presence: true
    # validates :date, presence: true
    # validates :time, presence: true
    belongs_to :user
    has_one_attached :payment_proof
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :bookings
         
         enum role: [:user, :admin]

         has_one_attached :avatar

  def avatar_thumbnail
    avatar.variant("150x150!").processed
  end

         
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController 

    def home
        
    end

    def users
        @users = User.all
    end

    def show
        @user = User.find_by(id: params[:id])
        if @user == nil 
            flash[:notice] = "User Not Found !"
        end

    end

    def destroy
        @user = User.find_by(id: params[:id])
        if @user
            @user.destroy 
            flash[:notice] = "User was successfully deleted !"
            redirect_to admin_users_path
        else 
            flash[:notice] = "User Not Found !"
        end
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters,
        if: :devise_controller?
            
        protected
        
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up , keys: [:avatar])
            devise_parameter_sanitizer.permit(:account_update , keys: [:avatar])
        end


end

app/controllers/bookings_controller.rb
require "prawn"

class BookingsController < ApplicationController 
    before_action :authenticate_user! 
    def new
        @booking = Booking.new
    end
    
    def create
        @booking = Booking.new(booking_params)
        if @booking.save
            flash[:notice] = "Booking was successfully done !"
            redirect_to booking_path(@booking)            
        else
            render 'new' 
        end
        
    end

    def show 
        @booking = Booking.find_by(id: params[:id])
        if @booking == nil 
            flash[:notice] = "Booking not found !"
        end
    end

    def index
        @bookings = Booking.all
    end

    def destroy
        @booking = Booking.find(params[:id])
        if @booking
            @booking.destroy
            flash[:notice] = "Booking was successfully deleted !"
            redirect_to bookings_path
        else 
            flash[:notice] = "Booking not found !"
        end 
    end

    def download_pdf
        booking = Booking.find(params[:id])
        if booking 
            send_data generate_pdf(booking),
                filename: "ticket.pdf",
                type: "application/pdf"
        else  
            flash[:notice] = "Unable to dowload Ticket !"
    end
    
    private 
    def generate_pdf(booking)
        Prawn::Document.new do
          text "Movie Booking App", align: :center
          text "User email : #{booking.user.email}", align: :center
          text "Place : #{booking.place}", align: :center
          text "Movie : #{booking.movie}", align: :center
          text "Date : #{booking.date}", align: :center
          text "Time : #{booking.time}", align: :center
        end.render
      end

    private 
        def booking_params 
            params.require(:booking).permit(:place , :movie , :date , :time, :user_id, :payment_proof)
        end
end 

app/controllers/pages_controller.rb


class PagesController < ApplicationController
    
    def home
        
    end

    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/home.html.erb
<h1>Welcome Admin !!!</h1>
<p>
    <%= link_to "Show All Bookings" , bookings_path%>
</p>
<p>
    <%= link_to "Show All Users" , admin_users_path%>
</p>

app/views/admins/show.html.erb
<h1>User</h1>   

<%= image_tag @user.avatar, width: "10%", height: "10%" if @user.avatar.attached?%>

<p>
        User ID --> <%= @user.id%><br>
</p>
<p>
        User E-Mail --> <%= @user.email%><br>
</p>
<table class = "table table-striped">
    <tr>
        <th>Movie Booked</th>
        <th>Place</th>
    </tr>
    <% @user.bookings.each do |booking|%>
        <tr>
            <td><%= booking.movie%></td>
            <td><%= booking.place%></td>
        </tr>
    <% end %>
    
</table>>


<%= link_to "Destroy", admin_destroy_user_path(@user), method: :delete, data: { confirm: "You sure?" } %>

app/views/admins/users.html.erb
<h1>Users Registered</h1>
<table class="table table-striped">
    <tr>
        <th>User ID</th>
        <th>User E-Mail</th>
    </tr>
    <% @users.each do |user|%>
        <tr>
            <td>
                <%= user.id%>
            </td>
            <td>
                <%= user.email%>
            </td>
            <td>
                <%= link_to "Show" , admin_users_show_path(user)%>
            </td>
            <td>
                <%= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %>
            </td>

            
        </tr>
    
    <% end %>
    

</table>

app/views/bookings/index.html.erb
<h1>My Bookings</h1><br>

<%= image_tag current_user.avatar, width: "10%" , height: "10%" if current_user.role != 'admin' and current_user.avatar.attached?%>

<%# <p><%= current_user.inspect%>
<p><%= link_to "New Booking" , new_booking_path%></p><br>
<table class="table table-striped">
    <tr>
        <th>Place</th>
        <th>Movie</th>
        <th>Date</th>
        <th>Time</th>
    </tr>
    <% if current_user.role == 'admin'%>
        <% @bookings.each do |booking| %>
    
        <tr>
            <td><%= booking.place %></td>
            <td><%= booking.movie %></td>
            <td><%= booking.date %></td>
            <td><%= booking.time %></td>
            <td><%= link_to "Show", booking_path(booking)%></td>
            <td><%= link_to 'Delete', booking_path(booking), :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>

    <% end %>
    <% else %>
    <% @bookings.each do |booking| %>
        <%if booking.user_id == current_user.id%>
        <tr>
            <td><%= booking.place %></td>
            <td><%= booking.movie %></td>
            <td><%= booking.date %></td>
            <td><%= booking.time %></td>     
            <td><%= link_to "Show", booking_path(booking)%></td>       
        </tr>
        
        <% end %>
        
    <%end%>
<% end %>



</table>



app/views/bookings/new.html.erb
<div>
<h1>New Booking</h1>
<% if @booking.errors.any?%>
    <p>Following errors occuerd</p>
    <ul>
        <% @booking.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
        <%end%>
    </ul>
<%end%>

<%= form_for @booking do |f|%>
        <p><%= f.label :place%><br>
        <%= f.text_field :place%>
        </p>
        <p><%= f.label :movie%><br>
        <%= f.text_field :movie%>
        </p>
        <p><%= f.label :date%><br>
        <%= f.text_field :date%>
        </p>
        <p><%= f.label :time%><br>
        <%= f.text_field :time%>
        </p>
        <p>
        <%= f.number_field :user_id, id: :booking_user_id , value: current_user.id , type: :hidden%></p>
        <strong>Price : ₹100</strong>
        <p>Please attach your payment proof below:</p>
        <p><%= f.label :payment_proof%> ==>
        <%= f.file_field :payment_proof%>
        </p>
        <p>
            <%= f.submit%>
        </p>
<% end %>
<%= link_to "My Bookings" , bookings_path%>
</div>










app/views/bookings/show.html.erb
<h1>Booking Details</h1>
<p>
    place : <%= @booking.place%><br>
    movie : <%= @booking.movie%><br>
    date : <%= @booking.date%><br>
    time : <%= @booking.time%><br>
    <%if current_user.role == 'admin'%>
        payment_proof : <%= image_tag @booking.payment_proof, width: "20%" , height: "20%"%>
    <%end%>
</p>
<p>
     <%= link_to "Download Ticket" , download_pdf_path%>  ||
    <%= link_to "My Bookings", bookings_path%>  || 
    <%= link_to "New Booking" , new_booking_path%>  || 
    <% if current_user.role == "admin"%>
        <%# <%= link_to "Delete", booking_path(@booking), :confirm => "Are you sure ?", :method => :delete %> 
        <%= link_to "Delete", booking_path(@booking), data: { confirm: 'Are You sure?' }, :method => :delete %>
    <% end %>
    
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Hello !</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        
        <% if user_signed_in? && current_user.role == "admin" %>
          <li class="nav-item">
              <%= link_to "Admin" , admin_path , class: "nav-link active"%>
            </li>
          <li class="nav-item">
            <%= link_to "Sign Out" , destroy_user_session_path, method: :delete , class: "nav-link active"%>
          </li>
          <% elsif user_signed_in? and current_user.role != "admin"%>
          <li class="nav-item">
          <%= link_to "My Bookings" , bookings_path, class: "nav-link active"%>
        </li>
          <li class="nav-item">
          <%= link_to "Edit Profile" , edit_user_registration_path, class: "nav-link active"%>
        </li>
          
        <li class="nav-item">
            <%= link_to "Sign Out" , destroy_user_session_path, method: :delete , class: "nav-link active"%>
          </li>
        <%else%>
        
        <li class="nav-item">
          <%= link_to "Sign Up" , new_user_registration_path , class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In" , new_user_session_path , class: "nav-link active"%>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |name,msg|%>
    <ul>
      <li><%=msg%></li>
    </ul>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/notice'%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Movie Ticket Booking App</h1>